export const projectList = [
  {
    id: "project1",
    title: "My Portfolio",
    features: ["Fully Responsive", "Scroll Events"],
    packages: [
      { name: "NextJS", image: "next.webp" },
      { name: "Typescript", image: "typescript.webp" },
      { name: "TailwindCSS", image: "tailwindcss.webp" },
    ],
    images: ["project1_1.jpg", "project1_2.jpg", "project1_3.jpg"],
    deployments: ["github"],
    github: "https://github.com/doraemon0807/hong-portfolio",
    link: "",
  },
  {
    id: "project2",
    title: "WeTube - Fullstack Video Sharing & Watching Platform",
    features: [
      "User Authentication",
      "Github/Kakao Login",
      "User Profile",
      "Add & Edit Comments",
      "Like & Unlike",
      "Record, Upload, Search Videos",
      "Video Player",
      "Light & Dark Mode",
    ],
    packages: [
      { name: "NodeJS", image: "nodejs.webp" },
      { name: "MongoDB", image: "mongo.webp" },
      { name: "ES6", image: "es6.webp" },
      { name: "Pug", image: "pug.webp" },
      { name: "Sass", image: "sass.webp" },
    ],
    images: ["project2_1.jpg", "project2_2.jpg", "project2_3.jpg"],
    deployments: ["Fly.io", "AWS S3", "Mongo Atlas"],
    github: "https://github.com/doraemon0807/wetube-reloaded",
    link: "https://wetube-reloaded.fly.dev/",
  },
  {
    id: "project3",
    title: "Mini Twitter - Serverless SNS Platform",
    features: [
      "User Authentication",
      "User Profile",
      "Post, Edit, Comment Tweets",
      "Like & Unlike",
    ],
    packages: [
      { name: "NextJS", image: "next.webp" },
      { name: "Typescript", image: "typescript.webp" },
      { name: "TailwindCSS", image: "tailwindcss.webp" },
      { name: "Prisma", image: "prisma.webp" },
    ],
    images: ["project3_1.jpg", "project3_2.jpg", "project3_3.jpg"],
    deployments: ["Serverless Deployments!", "CodeSandbox"],
    github: "https://github.com/doraemon0807/mini-twitter-clone",
    link: "https://4qouu5-3000.csb.app/",
  },
  {
    id: "project4",
    title: "Petflix - Movie Search Web with Movie API",
    features: ["Fetch Movie Database API", "Search Movies & TV Shows"],
    packages: [
      { name: "React", image: "react.webp" },
      { name: "Typescript", image: "typescript.webp" },
      { name: "Framer Motion", image: "motion.webp" },
    ],
    images: ["project4_1.jpg", "project4_2.jpg", "project4_3.jpg"],
    deployments: ["github"],
    github: "https://github.com/doraemon0807/petflix",
    link: "https://doraemon0807.github.io/petflix/",
  },
  {
    id: "project5",
    title: "Momentum - Chrome App",
    features: [
      "To-do List",
      "Daily Movie Suggestion",
      "Weather API",
      "Data Stored in Local Storage",
      "Light & Dark Mode",
    ],
    packages: [{ name: "Javascript", image: "js.webp" }],
    images: ["project5_1.jpg", "project5_2.jpg", "project5_3.jpg"],
    deployments: ["github"],
    github: "https://github.com/doraemon0807/momentum",
    link: "https://doraemon0807.github.io/momentum/",
  },
  {
    id: "project6",
    title: "PaintJS - 2D Painting App",
    features: ["Painting on Canvas", "Images Saving"],
    packages: [{ name: "Javascript", image: "js.webp" }],
    images: ["project6_1.jpg", "project6_2.jpg", "project6_3.jpg"],
    deployments: ["github"],
    github: "https://github.com/doraemon0807/paintjs",
    link: "",
  },
];
