export const projectList = [
  {
    id: "project1",
    title: "My Portfolio",
    function: ["Fully Responsive", "Light & Dark Mode"],
    package: ["NextJS", "Typescript", "TailwindCSS"],
    image: ["project1_1.jpg", "project1_2.jpg", "project1_3.jpg"],
    deployment: ["github"],
    github: "https://github.com/doraemon0807/hong-portfolio",
    link: "",
  },
  {
    id: "project2",
    title: "WeTube - Fullstack Video Sharing & Watching Platform",
    function: [
      "User Authentication",
      "Github/Kakao Login",
      "User Profile",
      "Add & Edit Comments",
      "Like & Unlike",
      "Record, Upload, Search Videos",
      "Video Player",
      "Light & Dark Mode",
    ],
    package: ["NodeJS", "MongoDB", "ES6", "Express", "Pug", "SCSS"],
    image: ["project2_1.jpg", "project2_2.jpg", "project2_3.jpg"],
    deployment: ["", "AWS S3", "Mongo Altlas"],
    github: "https://github.com/doraemon0807/wetube-reloaded",
    link: "https://wetube-reloaded.fly.dev/",
  },
  {
    id: "project3",
    title: "Mini Twitter - Serverless SNS Platform",
    function: [
      "User Authentication",
      "User Profile",
      "Post, Edit, Comment Tweets",
      "Like & Unlike",
    ],
    package: ["NextJS", "Typescript", "Prisma"],
    image: ["project3_1.jpg", "project3_2.jpg", "project3_3.jpg"],
    deployment: ["Serverless Deployment!", "CodeSandbox"],
    github: "https://github.com/doraemon0807/mini-twitter-clone",
    link: "https://4qouu5-3000.csb.app/",
  },
  {
    id: "project4",
    title: "Petflix - Movie Search Web with Movie API",
    function: ["Fetch Movie Database API", "Search Movies & TV Shows"],
    package: ["React", "Typescript", "Framer Motion"],
    image: ["project4_1.jpg", "project4_2.jpg", "project4_3.jpg"],
    deployment: ["github"],
    github: "https://github.com/doraemon0807/petflix",
    link: "https://doraemon0807.github.io/petflix/",
  },
  {
    id: "project5",
    title: "Momentum - Chrome App",
    function: [
      "To-do List",
      "Daily Movie Suggestion",
      "Weather API",
      "Data Stored in Local Storage",
      "Light & Dark Mode",
    ],
    package: ["Javascript"],
    image: ["project5_1.jpg", "project5_2.jpg", "project5_3.jpg"],
    deployment: ["github"],
    github: "https://github.com/doraemon0807/momentum",
    link: "https://doraemon0807.github.io/momentum/",
  },
  {
    id: "project6",
    title: "PaintJS - 2D Painting App",
    function: ["Painting on Canvas", "Image Saving"],
    package: ["Javascript"],
    image: ["project6_1.jpg", "project6_2.jpg", "project6_3.jpg"],
    deployment: ["github"],
    github: "https://github.com/doraemon0807/paintjs",
    link: "",
  },
];
